=== jackzhch/Internet-Technology---CMU/HW 1/SchedulingWithStax/build/classes/schedule.xsd
<?xml version="1.0" encoding="utf-8"?>   <!-- urlList.xsd -->
<schema 
   xmlns="http://www.w3.org/2001/XMLSchema"
   xmlns:co="http://www.andrew.cmu.edu/mm6"
   targetNamespace="http://www.andrew.cmu.edu/mm6"
   elementFormDefault="qualified"
   >
   <annotation>
      <documentation>This is the schedule XSDL document. 
      </documentation>
   </annotation>
   
   <simpleType name="startType">
       <restriction base="time"/>
   </simpleType>

   <simpleType name="endType">
       <restriction base="time"/>
   </simpleType>

    <complexType name="intervalType">
       <sequence>
          <element name = "start" type="co:startType"/>
          <element name = "end" type="co:endType"/>
       </sequence>
   </complexType>

   <complexType name="openSlotType">
       <sequence>
          <element name = "openSlot"  maxOccurs= "unbounded" type="co:intervalType"/>
       </sequence>
   </complexType>

   <complexType name="dayListType">
       <sequence>
          <element name = "Monday" type="co:openSlotType"/>
          <element name = "Tuesday" type="co:openSlotType"/>
          <element name = "Wednesday" type="co:openSlotType"/>
          <element name = "Thursday" type="co:openSlotType"/>
          <element name = "Friday" type="co:openSlotType"/>
          <element name = "Saturday" type="co:openSlotType"/>
          <element name = "Sunday" type="co:openSlotType"/>
       </sequence>
   </complexType>   
   
   <element name="schedule" type="co:dayListType"/>
  </schema>

=== jackzhch/Internet-Technology---CMU/HW 1/SchedulingWithStax/build/classes/schedule1.xml
<?xml version="1.0" encoding="UTF-8"?>  
<schedule xmlns="http://www.andrew.cmu.edu/mm6" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:schemaLocation="http://www.andrew.cmu.edu/mm6  
schedule.xsd"
>
<Monday>
   <openSlot>
     <start>09:00:00</start>
     <end>10:00:00</end>
   </openSlot>
   <openSlot>
       <start>13:00:00</start>
       <end>14:00:00</end>
   </openSlot>
</Monday>
 <Tuesday>  
	<openSlot>
       <start>18:58:00</start>
       <end>19:58:00</end>
   </openSlot>
	<openSlot>
       <start>21:58:00</start>
       <end>22:58:00</end>
   </openSlot>
</Tuesday>
<Wednesday>
   <openSlot>
       <start>09:00:00</start>
       <end>10:00:00</end>
   </openSlot>
   <openSlot>
       <start>11:00:00</start>
       <end>13:00:00</end>
   </openSlot>
   <openSlot>
       <start>14:00:00</start>
       <end>16:00:00</end>
   </openSlot>
</Wednesday>
<Thursday>
   <openSlot>
       <start>09:00:00</start>
       <end>10:00:00</end>
   </openSlot>
</Thursday>
<Friday>
   <openSlot>
       <start>11:00:00</start>
       <end>14:00:00</end>
   </openSlot>
</Friday>
<Saturday>
   <openSlot>
       <start>09:00:00</start>
       <end>10:00:00</end>
   </openSlot>
   <openSlot>
       <start>11:15:00</start>
       <end>12:15:00</end>
   </openSlot>
</Saturday>
<Sunday>
   <openSlot>
       <start>09:00:00</start>
       <end>10:00:00</end>
   </openSlot>
   <openSlot>
       <start>13:00:00</start>
       <end>17:00:00</end>
   </openSlot>
</Sunday>
</schedule>
